export const BRAND = {
  name: 'Fabricators',
  handle: 'fabricators_pk',
  tagline: 'Crafting Your Vision Into Steel Reality',
  phone: '+92321-7337993',
  whatsapp: '923217337993',
  whatsappLink: 'https://wa.me/923217337993?text=Hello%20Fabricators!%20I%20am%20interested%20in%20your%20fabrication%20services.',
  instagram: 'https://www.instagram.com/fabricators_pk',
  facebook: 'https://www.facebook.com/Fabricators.pk',
  youtube: 'https://www.youtube.com/@fabricators_pk',
  linkedin: 'https://www.linkedin.com/in/fabricators-0105a61a7/',
  address: 'Samsani Road Near Hanjarwaal (Syed Kabir Ali Shah Road), Lahore, Pakistan 53700',
  city: 'Lahore',
  country: 'Pakistan',
  email: 'fabricators.ceo@gmail.com',
  website: 'https://www.fabricators.pk',
  serviceAreas: ['Lahore', 'Gujranwala', 'Rawalpindi', 'Peshawar', 'All over Pakistan'],
  mission: 'To provide flexible, tailor-catered fabrication services suitable for a wide spectrum of the market.',
  vision: "To be Pakistan's most trusted fabrication partner for food businesses and commercial ventures.",
}

export const SERVICES = [
  {
    id: 'food-street-carts',
    title: 'Food Street Carts',
    image: '/images/food-street-carts.jpg',
    alt: 'Custom stainless steel food street cart by Fabricators Pakistan',
    icon: 'Truck',
    shortDesc: 'Mobile custom-built stainless steel food carts for street vendors.',
    fullDesc: 'We design and fabricate highly durable, mobile stainless steel food carts tailored to your specific menu requirements. Whether you are selling burgers, fries, or traditional street food, our carts are built to withstand the elements while providing a hygienic and efficient workspace.',
    features: ['Food-grade stainless steel', 'Custom storage compartments', 'Built-in waste management', 'Weather-resistant roofing options'],
  },
  {
    id: 'fries-counter',
    title: 'Fries Counter',
    image: '/images/fries-counter.jpg',
    alt: 'Stainless steel fries counter with fryer space by Fabricators',
    icon: 'Flame',
    shortDesc: 'Stainless steel fries counters with integrated fryer space.',
    fullDesc: 'Our specialized fries counters are designed for high-volume output with dedicated fryer spaces and oil drainage systems. Built from food-grade stainless steel, they are easy to clean and built to last in demanding commercial environments.',
    features: ['Integrated fryer cutouts', 'Oil-drip trays', 'Easy-to-clean surfaces', 'Ventilation ready'],
  },
  {
    id: 'custom-food-stalls',
    title: 'Custom Food Stalls',
    image: '/images/custom-food-stalls.jpg',
    alt: 'Custom BBQ shawarma and juice stall fabrication Pakistan',
    icon: 'Store',
    shortDesc: 'BBQ, shawarma, juice, and chaat stalls built to order.',
    fullDesc: 'We fabricate specialized setups for BBQ, Shawarma, Juice bars, and Chaat stalls ensuring optimal workflow and eye-catching aesthetics. Every stall is custom designed to match your brand and operational needs.',
    features: ['Specialized equipment mounts', 'Branding and signage integration', 'Ergonomic workflow design', 'Heavy-duty casters for mobility'],
  },
  {
    id: 'restaurant-kitchen',
    title: 'Restaurant Kitchen Equipment',
    image: '/images/restaurant-kitchen.jpg',
    alt: 'Commercial restaurant kitchen equipment fabricated in stainless steel',
    icon: 'ChefHat',
    shortDesc: 'Work tables, shelves, exhaust hoods, and commercial sinks.',
    fullDesc: 'Industrial-grade stainless steel fabrication for commercial kitchens meeting strict health and safety standards. From single work tables to complete kitchen fitouts, we deliver precision-built equipment for restaurants of all sizes.',
    features: ['Custom dimensions', 'Heavy-gauge steel construction', 'Seamless welding for hygiene', 'Complete kitchen fit-outs'],
  },
  {
    id: 'signage-branding',
    title: 'Signage & Branding',
    image: '/images/signage-branding.jpg',
    alt: 'Laser cut steel and acrylic business signage by Fabricators',
    icon: 'PenTool',
    shortDesc: 'Laser-cut steel and acrylic signage for your business.',
    fullDesc: 'Precision laser cutting to create stunning steel, aluminum, and acrylic signs that bring your brand to life. We offer LED backlighting, custom typography, and weatherproof finishes to ensure your signage stands out day and night.',
    features: ['Precision laser cutting', 'LED backlighting integration', 'Weatherproof finishes', 'Custom typography and logos'],
  },
  {
    id: 'general-fabrication',
    title: 'General Fabrication',
    image: '/images/general-fabrication.jpg',
    alt: 'General steel fabrication gates grills and railings by Fabricators',
    icon: 'Wrench',
    shortDesc: 'Gates, grills, railings, décor, and industrial parts.',
    fullDesc: 'Comprehensive general fabrication including architectural gates, security grills, staircase railings, and custom industrial parts. If it is steel, we can build it — from decorative interior pieces to heavy structural components.',
    features: ['Architectural metalwork', 'Structural steel fabrication', 'Custom decorative pieces', 'Industrial repair and welding'],
  },
]

export const PRODUCTS = [
  { id: 'p1',  name: 'SS Fries Counter Single Basket', description: 'Compact stainless steel counter designed for a single commercial fryer. Ideal for small setups.',                      category: 'Counters',   tag: 'Popular'     },
  { id: 'p2',  name: 'SS Fries Counter Double Basket', description: 'High-capacity fries counter accommodating double fryers with extended prep area.',                                    category: 'Counters',   tag: 'Best Seller' },
  { id: 'p3',  name: 'Mobile Food Cart Standard',      description: 'Durable push-cart with basic storage and prep counter. Perfect for starting a street food business.',                category: 'Food Carts', tag: ''            },
  { id: 'p4',  name: 'Mobile Food Cart Premium',       description: 'Upgraded food cart featuring a protective roof, built-in LED lighting, and custom branding panels.',                 category: 'Food Carts', tag: 'Premium'     },
  { id: 'p5',  name: 'Shawarma Counter',               description: 'Specialized counter with reinforced mounts for vertical broilers and built-in salad prep station.',                  category: 'Counters',   tag: ''            },
  { id: 'p6',  name: 'BBQ Stall Complete Setup',       description: 'Heavy-duty steel stall featuring a built-in charcoal grill, ash tray, and exhaust canopy.',                         category: 'Custom',     tag: ''            },
  { id: 'p7',  name: 'Juice Counter',                  description: 'Hygienic setup with built-in ice bins, fruit display racks, and easy-clean drainage.',                              category: 'Counters',   tag: ''            },
  { id: 'p8',  name: 'Chaat Stall',                    description: 'Traditional multi-compartment stall designed for serving chaat and gol gappay hygienically.',                       category: 'Food Carts', tag: ''            },
  { id: 'p9',  name: 'Commercial Kitchen Work Table',  description: 'Heavy-gauge stainless steel prep table with adjustable undershelf and bullet feet.',                                 category: 'Kitchen',    tag: 'Essential'   },
  { id: 'p10', name: 'Custom Exhaust Hood',            description: 'Industrial kitchen exhaust hood with baffle filters, custom-sized to your cooking line.',                            category: 'Kitchen',    tag: ''            },
  { id: 'p11', name: 'Food Truck Interior Fitout',     description: 'Complete custom stainless steel lining, counters, and equipment installation for food trucks.',                      category: 'Custom',     tag: 'Project'     },
  { id: 'p12', name: 'Display Counter',                description: 'Glass and steel display counter for bakeries and cafes, available in heated or ambient setups.',                     category: 'Counters',   tag: ''            },
]

export const STATS = [
  { value: '500+', label: 'Projects Completed'  },
  { value: '10+',  label: 'Years Experience'    },
  { value: '4',    label: 'Cities Served'       },
  { value: '92%',  label: 'Client Satisfaction' },
]

export const TESTIMONIALS = [
  { id: 1, name: 'Ahmed Raza',    city: 'Lahore',     text: 'Fabricators transformed my idea into a stunning mobile food cart. The build quality is exceptional and the stainless steel finish is top-notch. Highly recommended!' },
  { id: 2, name: 'Usman Ali',     city: 'Gujranwala', text: 'We ordered a complete commercial kitchen setup for our new restaurant. Work tables and exhaust hoods delivered on time and fit perfectly. True professionals.'       },
  { id: 3, name: 'Fatima Sheikh', city: 'Islamabad',  text: 'The custom signage they created for my café gave it that premium industrial look I was aiming for. The attention to detail in laser cutting is brilliant.'           },
]

export const GALLERY = [
  { id: 'g1',  title: 'SS Kitchen Cabinets',     category: 'Kitchen',  location: 'DHA, Lahore',         image: '/images/kitchen-cabinets.jpg',         alt: 'Stainless steel kitchen cabinets DHA Lahore'        },
  { id: 'g2',  title: 'SS Kitchen Render',        category: 'Kitchen',  location: 'Gulberg, Lahore',     image: '/images/kitchen-render.jpg',           alt: 'Stainless steel kitchen render Gulberg Lahore'      },
  { id: 'g3',  title: 'Kitchen Cabinet Setup',    category: 'Kitchen',  location: 'Bahria Town',         image: '/images/kitchen-cabinet-setup.jpg',    alt: 'Kitchen cabinet setup Bahria Town Lahore'           },
  { id: 'g4',  title: 'Premium Fries Counter',    category: 'Counters', location: 'Johar Town, Lahore',  image: '/images/premium-fries-counter.jpg',    alt: 'Premium stainless steel fries counter Johar Town'   },
  { id: 'g5',  title: 'Fries Counter Setup',      category: 'Counters', location: 'Model Town, Lahore',  image: '/images/fries-counter-setup.jpg',      alt: 'Fries counter setup Model Town Lahore'              },
  { id: 'g6',  title: 'Display Counter',          category: 'Counters', location: 'Wapda Town, Lahore',  image: '/images/display-counter.jpg',          alt: 'Steel display counter Wapda Town Lahore'            },
  { id: 'g7',  title: 'Mobile Food Cart',         category: 'Carts',    location: 'Anarkali, Lahore',    image: '/images/mobile-food-cart.jpg',         alt: 'Mobile stainless steel food cart Anarkali Lahore'   },
  { id: 'g8',  title: 'Food Cart Premium',        category: 'Carts',    location: 'DHA Phase 5, Lahore', image: '/images/food-cart-premium.jpg',        alt: 'Premium food cart with roof DHA Phase 5 Lahore'     },
  { id: 'g9',  title: 'Mobile Cart Standard',     category: 'Carts',    location: 'Gujranwala',          image: '/images/mobile-cart-standard.jpg',     alt: 'Standard mobile food cart Gujranwala'               },
  { id: 'g10', title: 'Restaurant Kitchen Setup', category: 'Kitchen',  location: 'Gulberg 3, Lahore',   image: '/images/restaurant-kitchen-setup.jpg', alt: 'Full restaurant kitchen setup Gulberg 3 Lahore'     },
  { id: 'g11', title: 'Commercial Kitchen',       category: 'Kitchen',  location: 'Rawalpindi',          image: '/images/commercial-kitchen.jpg',       alt: 'Commercial kitchen fabrication Rawalpindi'          },
  { id: 'g12', title: 'Full Kitchen Fitout',      category: 'Kitchen',  location: 'Islamabad',           image: '/images/full-kitchen-fitout.jpg',      alt: 'Complete kitchen fitout stainless steel Islamabad'  },
]
